title:  Nay Petrucelli
description: >- 
  Hi, thanks for stopping by. â˜• â˜•
# logo: 
url: "https://nayp3.github.io"
# theme: jekyll-theme-cayman
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


ğŸ
